apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app.kubernetes.io/name: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
    type: LoadBalancer  
